// Generated by CoffeeScript 1.7.1

/*
複数行コメント
コンパイル時にも残る
 */
var a, aaa, arr, b, bbb, c, ccc, ddd, flag, func1, func2, func3, func4, i, memoize, obj1, obj2, test, val, _i, _j, _k, _len;

test = function() {
  var a, i;
  a = test;
  i = a + 'test';
  return false;
};

for (i = _i = 0; _i < 10; i = ++_i) {
  console.log(i);
}

arr = ["a", "b", "c", "d", "e"];

for (i = _j = 0, _len = arr.length; _j < _len; i = ++_j) {
  val = arr[i];
  console.log("" + i + ": " + val);
}

for (_k = 0; _k < 10; _k++) {
  console.log(_i);
}


/*
 * ドックコメント（？）も書いておけたりとか
 * @param {Number} param1 引数1
 * @return {Number} 引数1を2乗した数値
 */

func1 = function(x, y) {
  if (y == null) {
    y = 1;
  }
  return x + y;
};

func2 = function(x, y) {
  if (y == null) {
    y = 1;
  }
  return x + y;
};

func3 = function(x, y) {
  if (y == null) {
    y = 1;
  }
  return x + y;
};

func1(1);

func1(1, 1);

func1(1);

func1(1, 1);

func4 = function() {
  return 1;
};

a = func4();

b = func4;

a = [1, 2, 3];

b = [1, 2, 3];

c = [1, 2, 3];

obj1 = {
  a: 1,
  b: 'str'
};

obj2 = {
  a: 1,
  b: 2,
  c: {
    d: 'd'
  },
  "typeof": 'str_typeof'
};

obj1.a;

obj1.b;

obj2.a;

obj2["typeof"];

if (true) {
  alert('true');
} else {
  alert('false');
}

if (!false) {
  alert('false');
} else {
  alert('true');
}

if (true) {
  aaa = 0;
}

if (!false) {
  bbb = 1;
}

ccc = true ? 1 : 0;

ddd = true ? 1 : 0;

memoize = false;

memoize || (memoize = {});

flag = true;

flag && (flag = 1);
